# This is a config for E2B sandbox template.
# You can use template ID (vtr3n8sgncl3dumyvo1q) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vtr3n8sgncl3dumyvo1q") # Sync sandbox
# sandbox = await AsyncSandbox.create("vtr3n8sgncl3dumyvo1q") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vtr3n8sgncl3dumyvo1q')

team_id = "c1e22212-4c48-4c56-832f-b328f6dd906e"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "vtr3n8sgncl3dumyvo1q"
